---

- name: Get users via passwd
  ansible.builtin.command:
    cmd: "awk -F: '$3 >= 1000 && $3 != 65534 { print $1 }' /etc/passwd"
  changed_when: false
  register: local_users

- name: Filter out excluded users
  ansible.builtin.set_fact:
    filtered_users: >-
      {{
        local_users.stdout_lines
        | difference(local_users_excluded)
      }}

- name: Compute users to remove
  ansible.builtin.set_fact:
    obsolete_users: >-
      {{
        filtered_users
        | difference(local_users_users | map(attribute='name') | list)
      }}

- name: Apply users
  loop: "{{ local_users_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  ansible.builtin.include_tasks:
    file: apply_users.yml

- name: Remove users
  loop: "{{ obsolete_users }}"
  loop_control:
    loop_var: user
  ansible.builtin.include_tasks:
    file: remove_users.yml

...
